module Parameters where

-- gox-hs
import Gox.Tree.Type

-- linear
import Linear

-- vector
import qualified Data.Vector as V

toRad :: Double -> Double
toRad = (* (pi / 180))
{-# INLINE toRad #-}

defaultP :: Parameters
defaultP = Parameters
  { pShape          = TendFlame
  , pGScale         = 13
  , pGScaleV        = 3
  , pLevels         = 3
  , pRatio          = 0.015
  , pRatioPower     = 1.2
  , pFlare          = 0.6
  , pBaseSplits     = 0
  , pBaseSize       = V.fromList [0.3, 0.02, 0.02, 0.02]
  , pDownAngle      = toRad <$> V.fromList [-0, 60, 45, 45]
  , pDownAngleV     = toRad <$> V.fromList [-0, -50, 10, 10]
  , pRotate         = toRad <$> V.fromList [-0, 140, 140, 77]
  , pRotateV        = toRad <$> V.fromList [-0, 0, 0, 0]
  , pBranches       = V.fromList [1, 50, 30, 10]
  , pLength         = V.fromList [1, 0.3, 0.6, 0]
  , pLengthV        = V.fromList [0, 0, 0, 0]
  , pTaper          = V.fromList [1, 1, 1, 1]
  , pSegSplits      = V.fromList [0, 0, 0, 0]
  , pSplitAngle     = toRad <$> V.fromList [40, 0, 0, 0]
  , pSplitAngleV    = toRad <$> V.fromList [5, 0, 0, 0]
  , pCurveRes       = V.fromList [5, 5, 3, 1]
  , pCurve          = toRad <$> V.fromList [0, -40, -40, 0]
  , pCurveBack      = toRad <$> V.fromList [0, 0, 0, 0]
  , pCurveV         = toRad <$> V.fromList [20, 50, 75, 0]
  , pBendV          = toRad <$> V.fromList [-0, 50, 0, 0]
  , pBranchDist     = V.fromList [-0, 0, 0, 0]
  , pRadiusMod      = V.fromList [1, 1, 1, 1]
  , pLeafBlosNum    = 40
  , pLeafShape      = 0
  , pLeafScale      = 0.17
  , pLeafScaleX     = 1
  , pLeafBend       = 0.6
  , pBlossomShape   = 1
  , pBlossomScale   = 0
  , pBlossomRate    = 0
  , pTropism        = V3 0 0 0.5
  , pPruneRatio     = 0
  , pPruneWidth     = 0.5
  , pPruneWidthPeak = 0.5
  , pPrunePowerLow  = 0.5
  , pPrunePowerHigh = 0.5
  }

acerP :: Parameters
acerP = defaultP
  { pShape          = Flame
  , pGScale         = 10
  , pGScaleV        = 1
  , pLevels         = 3
  , pRatio          = 0.025
  , pRatioPower     = 1.5
  , pFlare          = 0.6
  , pBaseSplits     = -2
  , pBaseSize       = V.fromList [0.1, 0.4, 0.02, 0.02]
  , pDownAngle      = toRad <$> V.fromList [-0, 50, 50, 45]
  , pDownAngleV     = toRad <$> V.fromList [-0, 5, 5, 10]
  , pRotate         = toRad <$> V.fromList [-0, 140, 140, 77]
  , pRotateV        = toRad <$> V.fromList [-0, 0, 0, 0]
  , pBranches       = V.fromList [1, 6, 20, 5]
  , pLength         = V.fromList [1, 0.7, 0.3, 0]
  , pLengthV        = V.fromList [0, 0.05, 0.05, 0]
  , pTaper          = V.fromList [1, 1, 1, 1]
  , pSegSplits      = V.fromList [1.5, 1.5, 0, 0]
  , pSplitAngle     = toRad <$> V.fromList [50, 50, 0, 0]
  , pSplitAngleV    = toRad <$> V.fromList [5, 5, 0, 0]
  , pCurveRes       = V.fromList [6, 5, 3, 0]
  , pCurve          = toRad <$> V.fromList [0, 0, 0, 0]
  , pCurveBack      = toRad <$> V.fromList [0, 0, 0, 0]
  , pCurveV         = toRad <$> V.fromList [200, 100, 100, 0]
  , pBendV          = toRad <$> V.fromList [-0, 50, 0, 0]
  , pBranchDist     = V.fromList [-0, 0, 0, 0]
  , pLeafBlosNum    = 30
  , pLeafShape      = 5
  , pLeafScale      = 0.2
  , pLeafBend       = 0.3
  }                  

appleP :: Parameters
appleP = defaultP
  { pShape          = Cylindrical
  , pGScale         = 9
  , pGScaleV        = 2
  , pLevels         = 3
  , pRatio          = 0.02
  , pRatioPower     = 1.5
  , pFlare          = 0.9
  , pBaseSplits     = 0
  , pBaseSize       = V.fromList [0.15, 0.02, 0.02, 0.02]
  , pDownAngle      = toRad <$> V.fromList [-0, 60, 60, 45]
  , pDownAngleV     = toRad <$> V.fromList [-0, -30, 20, 30]
  , pRotate         = toRad <$> V.fromList [-0, 140, 140, 77]
  , pRotateV        = toRad <$> V.fromList [-0, 0, 0, 0]
  , pBranches       = V.fromList [1, 35, 25, 10]
  , pLength         = V.fromList [1, 0.5, 0.4, 0]
  , pLengthV        = V.fromList [0, 0, 0.1, 0]
  , pTaper          = V.fromList [1, 1, 1, 1]
  , pSegSplits      = V.fromList [0, 0.6, 0, 0]
  , pSplitAngle     = toRad <$> V.fromList [0, 20, 0, 0]
  , pSplitAngleV    = toRad <$> V.fromList [0, 10, 0, 0]
  , pCurveRes       = V.fromList [5, 10, 5, 0]
  , pCurve          = toRad <$> V.fromList [0, -20, 0, 0]
  , pCurveBack      = toRad <$> V.fromList [0, 0, 0, 0]
  , pCurveV         = toRad <$> V.fromList [70, 140, 100, 0]
  , pBendV          = toRad <$> V.fromList [-0, 50, 0, 0]
  , pBranchDist     = V.fromList [-0, 0, 0, 0]
  , pLeafBlosNum    = 50
  , pLeafShape      = 8
  , pLeafScale      = 0.17
  , pLeafBend       = 0.5
  , pBlossomShape   = 1
  , pBlossomScale   = 0.08
  , pBlossomRate    = 0.35
  , pTropism        = V3 0 0 2
  }                  

balsamFirP :: Parameters
balsamFirP = Parameters
  { pShape          = Spherical
  , pGScale         = 12
  , pGScaleV        = 2
  , pLevels         = 3
  , pRatio          = 0.015
  , pRatioPower     = 1.7
  , pFlare          = 0.2
  , pBaseSplits     = 0
  , pBaseSize       = V.fromList [0.05, 0.02, 0.02, 0.02]
  , pDownAngle      = toRad <$> V.fromList [-0, 50, 60, 45]
  , pDownAngleV     = toRad <$> V.fromList [-0, -45, 20, 30]
  , pRotate         = toRad <$> V.fromList [-0, 140, -125, -90]
  , pRotateV        = toRad <$> V.fromList [-0, 0, 20, 20]
  , pBranches       = V.fromList [1, 100, 75, 10]
  , pLength         = V.fromList [1, 0.5, 0.25, 0]
  , pLengthV        = V.fromList [0.2, 0, 0.1, 0]
  , pTaper          = V.fromList [1, 1, 1, 1]
  , pSegSplits      = V.fromList [0, 0, 0, 0]
  , pSplitAngle     = toRad <$> V.fromList [0, 0, 0, 0]
  , pSplitAngleV    = toRad <$> V.fromList [0, 0, 0, 0]
  , pCurveRes       = V.fromList [5, 5, 2, 0]
  , pCurve          = toRad <$> V.fromList [0, -40, 0, 0]
  , pCurveBack      = toRad <$> V.fromList [0, 0, 0, 0]
  , pCurveV         = toRad <$> V.fromList [20, 10, 40, 0]
  , pBendV          = toRad <$> V.fromList [-0, 10, 0, 0]
  , pBranchDist     = V.fromList [-0, 0, 0, 0]
  , pLeafBlosNum    = 100
  , pLeafShape      = 2
  , pLeafScale      = 0.13
  , pLeafScaleX     = 0.5
  , pLeafBend       = 0
  }                  

bambooP :: Parameters
bambooP = defaultP
  { pShape          = Envelope
  , pGScale         = 10
  , pGScaleV        = 2
  , pLevels         = 2
  , pRatio          = 0.005
  , pRatioPower     = 1
  , pFlare          = 0
  , pBaseSize       = V.fromList [0.4, 0.4, 0, 0]
  , pDownAngle      = toRad <$> V.fromList [-0, 30, 30, 30]
  , pDownAngleV     = toRad <$> V.fromList [-0, 10, 10, 10]
  , pRotate         = toRad <$> V.fromList [-0, 77, 77, 77]
  , pRotateV        = toRad <$> V.fromList [-0, 30, 0, 0]
  , pBranches       = V.fromList [50, 25, 0, 10]
  , pLength         = V.fromList [1, 0.2, 0, 0]
  , pLengthV        = V.fromList [0, 0.05, 0, 0]
  , pTaper          = V.fromList [1, 1, 1, 1]
  , pSegSplits      = V.fromList [0, 0, 0, 0]
  , pSplitAngle     = toRad <$> V.fromList [0, 0, 0, 0]
  , pSplitAngleV    = toRad <$> V.fromList [0, 0, 0, 0]
  , pCurveRes       = V.fromList [10, 5, 0, 1]
  , pCurve          = toRad <$> V.fromList [50, 30, 0, 0]
  , pCurveBack      = toRad <$> V.fromList [0, 0, 0, 0]
  , pCurveV         = toRad <$> V.fromList [70, 0, 0, 0]
  , pLeafBlosNum    = 20
  , pLeafShape      = 0
  , pLeafScale      = 0.3
  , pLeafScaleX     = 0.3
  , pLeafBend       = 0.1
  , pTropism        = V3 0 0 0
  }                  

blackOakP :: Parameters
blackOakP = defaultP
  { pShape          = Cylindrical
  , pGScale         = 10
  , pGScaleV        = 2
  , pLevels         = 3
  , pRatio          = 0.018
  , pRatioPower     = 1.25
  , pFlare          = 1.2
  , pBaseSize       = V.fromList [0.05, 0.02, 0.02, 0.02]
  , pDownAngle      = toRad <$> V.fromList [-0, 30, 45, 45]
  , pDownAngleV     = toRad <$> V.fromList [-0, -30, 10, 10]
  , pRotate         = toRad <$> V.fromList [-0, 80, 140, 140]
  , pRotateV        = toRad <$> V.fromList [-0, 20, 20, 20]
  , pBranches       = V.fromList [1, 30, 120, 0]
  , pLength         = V.fromList [1, 0.8, 0.3, 0.4]
  , pLengthV        = V.fromList [0, 0.1, 0.05, 0]
  , pTaper          = V.fromList [0.95, 1, 1, 1]
  , pSegSplits      = V.fromList [0.1, 0.1, 0.1, 0]
  , pSplitAngle     = toRad <$> V.fromList [10, 10, 10, 0]
  , pSplitAngleV    = toRad <$> V.fromList [0, 10, 10, 0]
  , pCurveRes       = V.fromList [8, 10, 3, 1]
  , pCurve          = toRad <$> V.fromList [0, 40, 0, 0]
  , pCurveBack      = toRad <$> V.fromList [0, -70, 0, 0]
  , pCurveV         = toRad <$> V.fromList [90, 150, -30, 0]
  , pBendV          = toRad <$> V.fromList [-0, 100, 0, 0]
  , pLeafBlosNum    = 45
  , pLeafShape      = 6
  , pLeafScale      = 0.2
  , pLeafScaleX     = 0.66
  , pLeafBend       = 0.3
  , pTropism        = V3 0 0 0.8
  }                  

blackTupeloP :: Parameters
blackTupeloP = Parameters
  { pShape          = Flame
  , pGScale         = 23
  , pGScaleV        = 5
  , pLevels         = 4
  , pRatio          = 0.015
  , pRatioPower     = 1.3
  , pFlare          = 1
  , pBaseSplits     = 0
  , pBaseSize       = V.fromList [0.2, 0.02, 0.02, 0.02]
  , pDownAngle      = toRad <$> V.fromList [-0, 60, 40, 45]
  , pDownAngleV     = toRad <$> V.fromList [-0, -40, 10, 10]
  , pRotate         = toRad <$> V.fromList [-0, 140, 140, 140]
  , pRotateV        = toRad <$> V.fromList [-0, 60, 50, 0]
  , pBranches       = V.fromList [1, 75, 25, 15]
  , pLength         = V.fromList [1, 0.3, 0.6, 0.2]
  , pLengthV        = V.fromList [0, 0.05, 0.1, 0]
  , pTaper          = V.fromList [1, 1, 1, 1]
  , pSegSplits      = V.fromList [0, 0, 0, 0]
  , pSplitAngle     = toRad <$> V.fromList [0, 0, 0, 0]
  , pSplitAngleV    = toRad <$> V.fromList [0, 0, 0, 0]
  , pCurveRes       = V.fromList [10, 10, 10, 1]
  , pCurve          = toRad <$> V.fromList [0, 0, -10, 0]
  , pCurveBack      = toRad <$> V.fromList [0, 0, 0, 0]
  , pCurveV         = toRad <$> V.fromList [40, 90, 150, 0]
  , pBendV          = toRad <$> V.fromList [-0, 100, 0, 0]
  , pBranchDist     = V.fromList [-0, 0, 0, 0]
  , pLeafBlosNum    = 20
  , pLeafShape      = 0
  , pLeafScale      = 0.2
  , pLeafScaleX     = 1
  , pLeafBend       = 0.3
  }                  

cambridgeOakP :: Parameters
cambridgeOakP = defaultP
  { pShape          = TaperedCylindrical
  , pGScale         = 20
  , pGScaleV        = 4
  , pLevels         = 4
  , pRatio          = 0.03
  , pRatioPower     = 2
  , pFlare          = 0.5
  , pBaseSplits     = 1
  , pBaseSize       = V.fromList [0.2, 0, 0, 0]
  , pDownAngle      = toRad <$> V.fromList [-0, 60, 60, 45]
  , pDownAngleV     = toRad <$> V.fromList [-0, -30, 30, 10]
  , pRotate         = toRad <$> V.fromList [-0, 110, 110, 110]
  , pRotateV        = toRad <$> V.fromList [-0, 50, 50, 0]
  , pBranches       = V.fromList [1, 15, 10, 50]
  , pLength         = V.fromList [1, 0.4, 0.6, 0.2]
  , pLengthV        = V.fromList [0, 0.1, 0.1, 0]
  , pTaper          = V.fromList [1, 1, 1, 1]
  , pSegSplits      = V.fromList [0.5, 0.5, 0.2, 0]
  , pSplitAngle     = toRad <$> V.fromList [50, 50, 50, 0]
  , pSplitAngleV    = toRad <$> V.fromList [20, 10, 10, 0]
  , pCurveRes       = V.fromList [10, 10, 10, 3]
  , pCurve          = toRad <$> V.fromList [0, 20, 0, 0]
  , pCurveBack      = toRad <$> V.fromList [0, 0, 0, 0]
  , pCurveV         = toRad <$> V.fromList [100, 400, 500, 100]
  , pBendV          = toRad <$> V.fromList [100, 100, 30, 0]
  , pBranchDist     = V.fromList [-0, 0, 0, 0]
  , pLeafBlosNum    = 15
  , pLeafShape      = 7
  , pLeafScale      = 0.13
  , pLeafScaleX     = 1
  , pLeafBend       = 0
  , pTropism        = V3 0 0 0.5
  , pPruneRatio     = 1
  , pPruneWidth     = 0.6
  , pPruneWidthPeak = 0.2
  , pPrunePowerLow  = 0.1
  , pPrunePowerHigh = 0.5
  }                  

douglasFirP :: Parameters
douglasFirP = defaultP
  { pShape          = Spherical
  , pGScale         = 40
  , pGScaleV        = 10
  , pLevels         = 3
  , pRatio          = 0.015
  , pRatioPower     = 1.2
  , pFlare          = 1
  , pBaseSize       = V.fromList [0.2, 0.1, 0.02, 0.02]
  , pDownAngle      = toRad <$> V.fromList [-0, 100, 40, 45]
  , pDownAngleV     = toRad <$> V.fromList [-0, -40, 10, 10]
  , pRotate         = toRad <$> V.fromList [-0, 140, 140, 140]
  , pRotateV        = toRad <$> V.fromList [-0, 60, 50, 0]
  , pBranches       = V.fromList [1, 250, 30, 0]
  , pLength         = V.fromList [1, 0.13, 0.4, 0]
  , pLengthV        = V.fromList [0, 0, 0.1, 0]
  , pTaper          = V.fromList [1, 1, 1, 1]
  , pSegSplits      = V.fromList [0, 0.5, 0, 0]
  , pSplitAngle     = toRad <$> V.fromList [0, 0, 0, 0]
  , pSplitAngleV    = toRad <$> V.fromList [0, 0, 0, 0]
  , pCurveRes       = V.fromList [2, 5, 3, 1]
  , pCurve          = toRad <$> V.fromList [0, -35, 0, 0]
  , pCurveBack      = toRad <$> V.fromList [0, 0, 0, 0]
  , pCurveV         = toRad <$> V.fromList [0, 90, 150, 0]
  , pBendV          = toRad <$> V.fromList [-0, 50, 0, 0]
  , pBranchDist     = V.fromList [-0, 0, 0, 0]
  , pLeafBlosNum    = 100
  , pLeafShape      = 2
  , pLeafScale      = 0.15
  , pLeafScaleX     =0.3
  , pLeafBend       = 0
  }                  

europeanLarchP :: Parameters
europeanLarchP = defaultP
  { pShape          = Spherical
  , pGScale         = 15
  , pGScaleV        = 7
  , pLevels         = 3
  , pRatio          = 0.015
  , pRatioPower     = 1.3
  , pFlare          = 0.3
  , pBaseSize       = V.fromList [0.25, 0.02, 0.02, 0.02]
  , pDownAngle      = toRad <$> V.fromList [-0, 60, 70, 30]
  , pDownAngleV     = toRad <$> V.fromList [-0, -50, 30, 15]
  , pRotate         = toRad <$> V.fromList [-0, 70, 70, 120]
  , pRotateV        = toRad <$> V.fromList [-0, 30, 30, 30]
  , pBranches       = V.fromList [1, 60, 50, 0]
  , pLength         = V.fromList [1, 0.25, 0.3, 0]
  , pLengthV        = V.fromList [0, 0, 0.1, 0]
  , pTaper          = V.fromList [1, 1, 1, 1]
  , pSegSplits      = V.fromList [0, 0, 0.15, 0]
  , pSplitAngle     = toRad <$> V.fromList [0, 0, 40, 0]
  , pSplitAngleV    = toRad <$> V.fromList [0, 0, 10, 0]
  , pCurveRes       = V.fromList [20, 17, 7, 1]
  , pCurve          = toRad <$> V.fromList [0, 20, 0, 0]
  , pCurveBack      = toRad <$> V.fromList [0, -100, 0, 0]
  , pCurveV         = toRad <$> V.fromList [60, 120, 0, 0]
  , pLeafBlosNum    = 200
  , pLeafShape      = 2
  , pLeafScale      = 0.07
  , pLeafScaleX     = 0.5
  , pLeafBend       = 0.1
  , pTropism        = V3 0 0 (-3)
  }                  

fanPalmP :: Parameters
fanPalmP = defaultP
  { pShape          = TaperedCylindrical
  , pGScale         = 5
  , pGScaleV        = 2
  , pLevels         = 2
  , pRatio          = 0.04
  , pRatioPower     = 1.3
  , pFlare          = 0
  , pBaseSize       = V.fromList [0.8, 0, 0, 0]
  , pDownAngle      = toRad <$> V.fromList [-0, 20, -10, 0]
  , pDownAngleV     = toRad <$> V.fromList [-0, -60, 10, 0]
  , pRotate         = toRad <$> V.fromList [-0, 160, 260, 0]
  , pRotateV        = toRad <$> V.fromList [-0, 40, 5, 0]
  , pBranches       = V.fromList [1, 50, 0, 0]
  , pLength         = V.fromList [1, 0.25, 0, 0]
  , pLengthV        = V.fromList [0, 0.05, 0, 0]
  , pTaper          = V.fromList [2.1, 1.4, 0, 0]
  , pSegSplits      = V.fromList [0, 0, 0, 0]
  , pSplitAngle     = toRad <$> V.fromList [0, 0, 0, 0]
  , pSplitAngleV    = toRad <$> V.fromList [0, 0, 0, 0]
  , pCurveRes       = V.fromList [6, 9, 0, 0]
  , pCurve          = toRad <$> V.fromList [10, 50, 0, 0]
  , pCurveBack      = toRad <$> V.fromList [0, -5, 0, 0]
  , pCurveV         = toRad <$> V.fromList [40, 30, 0, 0]
  , pBendV          = toRad <$> V.fromList [-0, 0, 0, 0]
  , pBranchDist     = V.fromList [-0, 0, 0, 0]
  , pLeafBlosNum    = -90
  , pLeafShape      = 10
  , pLeafScale      = 0.8
  , pLeafScaleX     = 0.05
  , pLeafBend       = 0
  , pTropism        = V3 0 0 (-1)
  }                  

hillCherryP :: Parameters
hillCherryP = defaultP
  { pShape          = Cylindrical
  , pGScale         = 13
  , pGScaleV        = 3
  , pLevels         = 3
  , pRatio          = 0.015
  , pRatioPower     = 1.3
  , pFlare          = 0.6
  , pBaseSplits     = -2
  , pBaseSize       = V.fromList [0.15, 0.02, 0.02, 0.02]
  , pDownAngle      = toRad <$> V.fromList [-0, 70, 60, 45]
  , pDownAngleV     = toRad <$> V.fromList [-0, 10, 20, 30]
  , pRotate         = toRad <$> V.fromList [-0, 140, 140, 77]
  , pRotateV        = toRad <$> V.fromList [-0, 0, 0, 0]
  , pBranches       = V.fromList [1, 25, 18, 10]
  , pLength         = V.fromList [0.8, 0.5, 0.6, 0]
  , pLengthV        = V.fromList [0, 0, 0.1, 0]
  , pTaper          = V.fromList [1, 1, 1, 1]
  , pSegSplits      = V.fromList [0.5, 0.3, 0, 0]
  , pSplitAngle     = toRad <$> V.fromList [40, 40, 0, 0]
  , pSplitAngleV    = toRad <$> V.fromList [5, 5, 0, 0]
  , pCurveRes       = V.fromList [10, 5, 8, 0]
  , pCurve          = toRad <$> V.fromList [30, -20, -40, 0]
  , pCurveBack      = toRad <$> V.fromList [-40, 40, 0, 0]
  , pCurveV         = toRad <$> V.fromList [150, 150, 150, 0]
  , pBendV          = toRad <$> V.fromList [150, 150, 250, 0]
  , pBranchDist     = V.fromList [-0, 0, 0, 0]
  , pLeafBlosNum    = 25
  , pBlossomShape   = 1
  , pBlossomScale   = 0.1
  , pBlossomRate    = 1
  , pTropism        = V3 0 0 (-1)
  , pPruneRatio     = 1
  , pPruneWidth     = 0.7
  , pPruneWidthPeak = 0.5
  , pPrunePowerLow  = 0.2
  , pPrunePowerHigh = 0.5
  }                  

lombardyPoplarP :: Parameters
lombardyPoplarP = Parameters
  { pShape          = Cylindrical
  , pGScale         = 25
  , pGScaleV        = 5
  , pLevels         = 3
  , pRatio          = 0.015
  , pRatioPower     = 1.2
  , pFlare          = 0.8
  , pBaseSize       = V.fromList [0.01, 0.1, 0.02, 0.02]
  , pDownAngle      = toRad <$> V.fromList [-0, 30, 30, 30]
  , pDownAngleV     = toRad <$> V.fromList [-0, 0, 10, 10]
  , pRotate         = toRad <$> V.fromList [-0, 77, 77, 77]
  , pRotateV        = toRad <$> V.fromList [-0, 15, 15, 15]
  , pBranches       = V.fromList [1, 60, 35, 10]
  , pLength         = V.fromList [1, 0.3, 0.4, 0]
  , pLengthV        = V.fromList [1, 0.3, 0.4, 0]
  , pTaper          = V.fromList [1, 1, 1, 1]
  , pCurveRes       = V.fromList [1, 3, 3, 1]
  , pCurve          = toRad <$> V.fromList [0, -20, -20, 0]
  , pCurveBack      = toRad <$> V.fromList [0, 0, 0, 0]
  , pCurveV         = toRad <$> V.fromList [0, 0, 40, 0]
  , pLeafBlosNum    = 30
  , pLeafShape      = 8
  , pLeafScale      = 0.3
  , pLeafScaleX     = 1
  , pLeafBend       = 0.7
  , pTropism        = V3 0 0 0.5
  }                  

palmP :: Parameters
palmP = defaultP
  { pShape          = TaperedCylindrical
  , pGScale         = 14
  , pGScaleV        = 3
  , pLevels         = 2
  , pRatio          = 0.015
  , pRatioPower     = 2
  , pFlare          = 0.3
  , pBaseSize       = V.fromList [0.95, 0.02, 0, 0]
  , pDownAngle      = toRad <$> V.fromList [-0, 60, 50, 0]
  , pDownAngleV     = toRad <$> V.fromList [-0, -80, -75, 0]
  , pRotate         = toRad <$> V.fromList [-0, 120, -120, 0]
  , pRotateV        = toRad <$> V.fromList [-0, 60, 20, 0]
  , pBranches       = V.fromList [1, 25, 0, 0]
  , pLength         = V.fromList [1, 0.3, 0, 0]
  , pLengthV        = V.fromList [0, 0.02, 0, 0]
  , pTaper          = V.fromList [2.15, 1, 0, 0]
  , pSegSplits      = V.fromList [0, 0, 0, 0]
  , pSplitAngle     = toRad <$> V.fromList [0, 0, 0, 0]
  , pSplitAngleV    = toRad <$> V.fromList [0, 0, 0, 0]
  , pCurveRes       = V.fromList [12, 9, 0, 0]
  , pCurve          = toRad <$> V.fromList [20, 40, 0, 0]
  , pCurveBack      = toRad <$> V.fromList [-10, 0, 0, 0]
  , pCurveV         = toRad <$> V.fromList [10, 20, 0, 0]
  , pBendV          = toRad <$> V.fromList [-0, 0, 0, 0]
  , pBranchDist     = V.fromList [-0, 0, 0, 0]
  , pLeafBlosNum    = 150
  , pLeafShape      = 10
  , pLeafScale      = 0.8
  , pLeafScaleX     = 0.12
  , pLeafBend       = 0
  , pTropism        = V3 0 0 (-3)
  }                  

quakingAspenP :: Parameters
quakingAspenP = defaultP
  { pShape          = Envelope
  , pGScale         = 13
  , pGScaleV        = 3
  , pLevels         = 3
  , pRatio          = 0.015
  , pRatioPower     = 1.2
  , pFlare          = 0.6
  , pBaseSplits     = 0
  , pBaseSize       = V.fromList [0.3, 0.02, 0.02, 0.02]
  , pDownAngle      = toRad <$> V.fromList [-0, 60, 60, 45]
  , pDownAngleV     = toRad <$> V.fromList [-0, -50, 20, 30]
  , pRotate         = toRad <$> V.fromList [-0, 140, 140, 77]
  , pRotateV        = toRad <$> V.fromList [-0, 0, 0, 0]
  , pBranches       = V.fromList [1, 50, 30, 1]
  , pLength         = V.fromList [1, 0.3, 0.6, 0]
  , pLengthV        = V.fromList [0, 0, 0.1, 0]
  , pTaper          = V.fromList [1, 1, 1, 1]
  , pSegSplits      = V.fromList [0, 0, 0, 0]
  , pSplitAngle     = toRad <$> V.fromList [40, 0, 0, 0]
  , pSplitAngleV    = toRad <$> V.fromList [5, 0, 0, 0]
  , pCurveRes       = V.fromList [5, 5, 5, 0]
  , pCurve          = toRad <$> V.fromList [0, -40, -60, 0]
  , pCurveBack      = toRad <$> V.fromList [0, 0, 0, 0]
  , pCurveV         = toRad <$> V.fromList [20, 100, 100, 0]
  , pBendV          = toRad <$> V.fromList [-0, 50, 0, 0]
  , pBranchDist     = V.fromList [-0, 0, 0, 0]
  , pLeafBlosNum    = 40
  , pLeafShape      = 3
  , pLeafScale      = 0.17
  , pLeafBend       = 0.6
  }                  

sassafrasP :: Parameters
sassafrasP = defaultP
  { pShape          = Cylindrical
  , pGScale         = 23
  , pGScaleV        = 7
  , pLevels         = 4
  , pRatio          = 0.02
  , pRatioPower     = 1.3
  , pFlare          = 0.5
  , pBaseSplits     = 0
  , pBaseSize       = V.fromList [0.2, 0.02, 0.02, 0.02]
  , pDownAngle      = toRad <$> V.fromList [-0, 90, 50, 45]
  , pDownAngleV     = toRad <$> V.fromList [-0, -10, 10, 10]
  , pRotate         = toRad <$> V.fromList [-0, 140, 140, 140]
  , pRotateV        = toRad <$> V.fromList [-0, 0, 0, 0]
  , pBranches       = V.fromList [1, 20, 20, 30]
  , pLength         = V.fromList [1, 0.4, 0.7, 0.4]
  , pLengthV        = V.fromList [0, 0, 0, 0]
  , pTaper          = V.fromList [1, 1, 1, 1]
  , pSegSplits      = V.fromList [0, 0, 0, 0]
  , pSplitAngle     = toRad <$> V.fromList [20, 0, 0, 0]
  , pSplitAngleV    = toRad <$> V.fromList [5, 0, 0, 0]
  , pCurveRes       = V.fromList [16, 15, 8, 3]
  , pCurve          = toRad <$> V.fromList [0, -60, -40, 0]
  , pCurveBack      = toRad <$> V.fromList [0, 30, 0, 0]
  , pCurveV         = toRad <$> V.fromList [60, 100, 150, 100]
  , pLeafBlosNum    = 15
  , pLeafShape      = 0
  , pLeafScale      = 0.25
  , pLeafScaleX     = 0.7
  , pLeafBend       = 0.3
  , pTropism        = V3 0 0 0.5
  }                  

silverrBirchP :: Parameters
silverrBirchP = defaultP
  { pShape          = 3
  , pGScale         = 20
  , pGScaleV        = 5
  , pLevels         = 3
  , pRatio          = 0.015
  , pRatioPower     = 1.5
  , pFlare          = 0.5
  , pBaseSplits     = 0
  , pBaseSize       = V.fromList [0.3, 0.1, 0.02, 0.02]
  , pDownAngle      = toRad <$> V.fromList [-0, 50, 40, 45]
  , pDownAngleV     = toRad <$> V.fromList [-0, -20, 10, 10]
  , pRotate         = toRad <$> V.fromList [-0, 140, 140, 140]
  , pRotateV        = toRad <$> V.fromList [-0, 60, 50, 0]
  , pBranches       = V.fromList [1, 30, 60, 0]
  , pLength         = V.fromList [1, 0.3, 0.4, 0]
  , pLengthV        = V.fromList [0, 0.05, 0.2, 0]
  , pTaper          = V.fromList [1, 1, 1, 1]
  , pSegSplits      = V.fromList [0, 0.3, 0, 0]
  , pSplitAngle     = toRad <$> V.fromList [15, 10, 0, 0]
  , pSplitAngleV    = toRad <$> V.fromList [0, 0, 0, 0]
  , pCurveRes       = V.fromList [10, 10, 10, 0]
  , pCurve          = toRad <$> V.fromList [0, 0, -10, 0]
  , pCurveBack      = toRad <$> V.fromList [0, 0, 0, 0]
  , pCurveV         = toRad <$> V.fromList [50, 150, 200, 0]
  , pBendV          = toRad <$> V.fromList [-0, 100, 0, 0]
  , pBranchDist     = V.fromList [-0, 0, 0, 0]
  , pLeafBlosNum    = 65
  , pLeafShape      = 3
  , pLeafScale      = 0.15
  , pLeafScaleX     = 1
  , pLeafBend       = 0.2
  , pTropism        = V3 0 0 (-2)
  }                  

smallPineP :: Parameters
smallPineP = defaultP
  { pShape          = Spherical
  , pGScale         = 6
  , pGScaleV        = 0.5
  , pLevels         = 2
  , pRatio          = 0.02
  , pRatioPower     = 1.3
  , pFlare          = 0.3
  , pBaseSize       = V.fromList [0.05, 0.02, 0.02, 0.02]
  , pDownAngle      = toRad <$> V.fromList [-0, 30, 30, 0]
  , pDownAngleV     = toRad <$> V.fromList [-0, -60, 10, 0]
  , pRotate         = toRad <$> V.fromList [-0, 140, 140, 0]
  , pRotateV        = toRad <$> V.fromList [-0, 30, 20, 0]
  , pBranches       = V.fromList [1, 70, 0, 0]
  , pLength         = V.fromList [1, 0.35, 0, 0]
  , pLengthV        = V.fromList [0, 0.05, 0, 0]
  , pTaper          = V.fromList [1, 1, 0, 0]
  , pSegSplits      = V.fromList [0, 2, 0, 0]
  , pSplitAngle     = toRad <$> V.fromList [0, -80, 0, 0]
  , pSplitAngleV    = toRad <$> V.fromList [0, -30, 0, 0]
  , pCurveRes       = V.fromList [5, 6, 0, 0]
  , pCurve          = toRad <$> V.fromList [0, -20, 0, 0]
  , pCurveBack      = toRad <$> V.fromList [0, 0, 0, 0]
  , pCurveV         = toRad <$> V.fromList [10, 90, 0, 0]
  , pBendV          = toRad <$> V.fromList [-0, 70, 0, 0]
  , pBranchDist     = V.fromList [-0, 3.5, 0, 0]
  , pLeafBlosNum    = 400
  , pLeafShape      = 2
  , pLeafScale      = 0.17
  , pLeafScaleX     = 0.3
  , pLeafBend       = 0
  , pTropism        = V3 0 0 0
  }                  

sphereTreeP :: Parameters
sphereTreeP = Parameters
  { pShape          = TaperedCylindrical
  , pGScale         = 6
  , pGScaleV        = 0
  , pLevels         = 3
  , pRatio          = 0.025
  , pRatioPower     = 1.5
  , pFlare          = 0.6
  , pBaseSplits     = 0
  , pBaseSize       = V.fromList [0.5, 0.02, 0.02, 0.02]
  , pDownAngle      = toRad <$> V.fromList [-0, 70, 45, 45]
  , pDownAngleV     = toRad <$> V.fromList [-0, 20, 10, 10]
  , pRotate         = toRad <$> V.fromList [-0, 100, 140, 77]
  , pRotateV        = toRad <$> V.fromList [-0, 0, 0, 0]
  , pBranches       = V.fromList [1, 70, 75, 10]
  , pLength         = V.fromList [1, 1, 1, 0]
  , pLengthV        = V.fromList [0, 0, 0, 0]
  , pTaper          = V.fromList [2, 1, 1, 1]
  , pSegSplits      = V.fromList [0, 0, 0, 0]
  , pSplitAngle     = toRad <$> V.fromList [40, 0, 0, 0]
  , pSplitAngleV    = toRad <$> V.fromList [5, 0, 0, 0]
  , pCurveRes       = V.fromList [5, 5, 3, 1]
  , pCurve          = toRad <$> V.fromList [0, 0, 0, 0]
  , pCurveBack      = toRad <$> V.fromList [0, 0, 0, 0]
  , pCurveV         = toRad <$> V.fromList [-40, 75, 75, 0]
  , pBendV          = toRad <$> V.fromList [-0, 50, 0, 0]
  , pBranchDist     = V.fromList [-0, 0, 0, 0]
  , pLeafBlosNum    = 25
  , pLeafShape      = 0
  , pLeafScale      = 0.17
  , pLeafScaleX     = 1
  , pLeafBend       = 0.3
  , pTropism        = V3 0 0 0
  , pPruneRatio     = 1
  , pPruneWidth     = 0.3
  , pPruneWidthPeak = 0.5
  , pPrunePowerLow  = 0.5
  , pPrunePowerHigh = 0.5
  }                  

weepingWillowP :: Parameters
weepingWillowP = defaultP
  { pShape          = Flame
  , pGScale         = 15
  , pGScaleV        = 3
  , pLevels         = 4
  , pRatio          = 0.03
  , pRatioPower     = 1.2
  , pFlare          = 0.75
  , pBaseSplits     = 2
  , pBaseSize       = V.fromList [0.05, 0.3, 0.05, 0.05]
  , pDownAngle      = toRad <$> V.fromList [-0, 40, 30, 20]
  , pDownAngleV     = toRad <$> V.fromList [-0, 10, 10, 10]
  , pRotate         = toRad <$> V.fromList [-0, -120, -120, 140]
  , pRotateV        = toRad <$> V.fromList [-0, 30, 30, 0]
  , pBranches       = V.fromList [1, 17, 25, 75]
  , pLength         = V.fromList [1, 0.35, 2.0, 0.1]
  , pLengthV        = V.fromList [0, 0.1, 0, 0]
  , pTaper          = V.fromList [1, 1, 1, 1]
  , pSegSplits      = V.fromList [0.2, 0.2, 0.1, 0]
  , pSplitAngle     = toRad <$> V.fromList [40, 30, 45, 0]
  , pSplitAngleV    = toRad <$> V.fromList [5, 10, 20, 0]
  , pCurveRes       = V.fromList [8, 16, 12, 2]
  , pCurve          = toRad <$> V.fromList [0, 40, 0, 0]
  , pCurveBack      = toRad <$> V.fromList [25, 0, 0, 0]
  , pCurveV         = toRad <$> V.fromList [90, 200, 0, 0]
  , pBendV          = toRad <$> V.fromList [0, 160, 0, 0]
  , pBranchDist     = V.fromList [-0, 0, 0, 0]
  , pRadiusMod      = V.fromList [1, 1, 0.1, 1]
  , pLeafBlosNum    = 20
  , pLeafShape      = 0
  , pLeafScale      = 0.13
  , pLeafScaleX     = 0.3
  , pLeafBend       = 0
  , pTropism        = V3 0 0 (-3)
  , pPruneRatio     = 1
  , pPruneWidth     = 0.4
  , pPruneWidthPeak = 0.6
  , pPrunePowerLow  = 0.001
  , pPrunePowerHigh = 0.5
  }                  

weepingWillow2P :: Parameters
weepingWillow2P = defaultP
  { pShape          = TaperedCylindrical
  , pGScale         = 15
  , pGScaleV        = 5
  , pLevels         = 4
  , pRatio          = 0.03
  , pRatioPower     = 2
  , pFlare          = 0.75
  , pBaseSplits     = 2
  , pBaseSize       = V.fromList [0.05, 0.3, 0.05, 0.05]
  , pDownAngle      = toRad <$> V.fromList [-0, 20, 30, 20]
  , pDownAngleV     = toRad <$> V.fromList [-0, 10, 10, 10]
  , pRotate         = toRad <$> V.fromList [-0, -120, -120, 140]
  , pRotateV        = toRad <$> V.fromList [-0, 30, 30, 0]
  , pBranches       = V.fromList [1, 25, 10, 300]
  , pLength         = V.fromList [0.8, 0.5, 1.5, 0.1]
  , pLengthV        = V.fromList [0, 0.1, 0, 0]
  , pTaper          = V.fromList [1, 1, 1, 1]
  , pSegSplits      = V.fromList [0.1, 0.2, 0.2, 0]
  , pSplitAngle     = toRad <$> V.fromList [3, 30, 45, 0]
  , pSplitAngleV    = toRad <$> V.fromList [0, 10, 20, 0]
  , pCurveRes       = V.fromList [8, 16, 12, 1]
  , pCurve          = toRad <$> V.fromList [0, 40, 0, 0]
  , pCurveBack      = toRad <$> V.fromList [20, 80, 0, 0]
  , pCurveV         = toRad <$> V.fromList [120, 90, 0, 0]
  , pBendV          = toRad <$> V.fromList [0, 0, 0, 0]
  , pBranchDist     = V.fromList [-0, 0, 0, 0]
  , pRadiusMod      = V.fromList [1, 1, 1, 1]
  , pLeafBlosNum    = 15
  , pLeafShape      = 0
  , pLeafScale      = 0.12
  , pLeafScaleX     = 0.2
  , pLeafBend       = 0
  , pTropism        = V3 0 0 (-3)
  , pPruneRatio     = 1
  , pPruneWidth     = 0.4
  , pPruneWidthPeak = 0.4
  , pPrunePowerLow  = 0.001
  , pPrunePowerHigh = 0.5
  }                  

